apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  project: default
  source:
    path: project/helm
    repoURL: https://github.com/vanthonglee/nd064_course_1
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default